// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCycBjiRYqj6uzzgmba6MbP1zaAfswup9U',
    appId: '1:594007996995:web:b06092e9bf761018e2b2f6',
    messagingSenderId: '594007996995',
    projectId: 'fireguard-ai',
    authDomain: 'fireguard-ai.firebaseapp.com',
    storageBucket: 'fireguard-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2lELN0slwo5d6dwdyPFycW1fZ-eKgS4',
    appId: '1:594007996995:android:5b130b7b288e1ccfe2b2f6',
    messagingSenderId: '594007996995',
    projectId: 'fireguard-ai',
    storageBucket: 'fireguard-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-hArqxU8wTKMJD3Z6GzpxUEIE4q0qwo',
    appId: '1:594007996995:ios:4a8f0f2a03cceec6e2b2f6',
    messagingSenderId: '594007996995',
    projectId: 'fireguard-ai',
    storageBucket: 'fireguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.fireguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-hArqxU8wTKMJD3Z6GzpxUEIE4q0qwo',
    appId: '1:594007996995:ios:4a8f0f2a03cceec6e2b2f6',
    messagingSenderId: '594007996995',
    projectId: 'fireguard-ai',
    storageBucket: 'fireguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.fireguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCycBjiRYqj6uzzgmba6MbP1zaAfswup9U',
    appId: '1:594007996995:web:d79515e5439be371e2b2f6',
    messagingSenderId: '594007996995',
    projectId: 'fireguard-ai',
    authDomain: 'fireguard-ai.firebaseapp.com',
    storageBucket: 'fireguard-ai.firebasestorage.app',
  );
}
