# Generated by Django 4.2.27 on 2026-02-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('building_id', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=10)),
                ('house', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('installed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FireDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('station_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('building_id', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=10)),
                ('house', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_limit', models.IntegerField()),
                ('auto_sprinkler', models.BooleanField(default=True)),
                ('notify_neighbours', models.BooleanField(default=True)),
                ('notify_authorities', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=100, unique=True)),
                ('action', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fireguard_ai.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.IntegerField()),
                ('flame', models.BooleanField()),
                ('temp', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.device')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100, unique=True)),
                ('incident_type', models.CharField(choices=[('fire', 'Fire'), ('gas', 'Gas Leak')], max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='fireguard_ai.userprofile'),
        ),
        migrations.CreateModel(
            name='BlockManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BlockIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=10)),
                ('house', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('secretary', 'Secretary'), ('chairman', 'Chairman')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fireguard_ai.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(max_length=30)),
                ('generated_at', models.DateTimeField()),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fireguard_ai.incident')),
            ],
        ),
    ]
