# Generated by Django 4.2.23 on 2026-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireguard_ai', '0003_userprofile_is_active_userprofile_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
