# Generated by Django 4.2.23 on 2026-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireguard_ai', '0004_userprofile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='sprinkler',
            field=models.BooleanField(default=False),
        ),
    ]
